spring:
  datasource:
    url: jdbc:h2:mem:prography
    username: sa
    password:
    driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
  jpa:
    open-in-view: false
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: create

# log4jdbc, Mybatis Console Log
logging:
  level:
    com:
      zaxxer:
        hikari: INFO
    javax:
      sql:
        DataSource: OFF
    jdbc:
      audit: OFF
      resultset: OFF
      resultsettable: DEBUG  #SQL ?? ??? Table? ??? ???.
      sqlonly: OFF      #SQL? ??? ???.
      sqltiming: DEBUG  #SQL? ????? ????.
      connection: OFF  # ??? ????
    org:
      hibernate:
        SQL: DEBUG
        type:
          descriptor:
            sql:
              BasicBinder: INFO
    root: INFO
server:
  port:8080