spring:
  datasource:
    #url: jdbc:h2:mem:prography;NON_KEYWORDS=USER
    url: jdbc:log4jdbc:h2:mem:prography;NON_KEYWORDS=USER
    username: sa
    password:
    #driver-class-name: org.h2.Driver
    driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
  jpa:
    open-in-view: false
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: create
    generate-ddl: true
    show-sql: true

  h2:
    console:
      enabled: true
      path: /h2-console
logging:
  level:
    sql: info


server:
  port:8080
